### PR TITLE
Styling main container

### PR DESCRIPTION
**Pull request by jamestucker1988**
trying to create a responsive menubar.

### CODE REVIEW

**Comment by jamestucker1988** [comment]
Fixed all the changes as asked by TSE Adaorachi. I enumerate the changes below.
1. Judicious use of ID's
2.Used Individual logos instead of an image as a whole and aligned text with it.
3. avoid the usage of the margin selector for aligning elements.
4.Judicious use of grids

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Comment by chelmerrox** [comment]
We've done most of the required changes.

1. enabled stickler app for this repo
2. writing a pull request with a short description of our project
3. fixed the html validation errors
4. made our web page responsive
5. tried to use DRY rule of programming

Our webpage is divided as such:
 1. navbar that includes the sign in button
 2. the main container that has:
  - the logo
  - other icons and texts beside them 
  - texts above the form
  - the form elements
  - other texts below the form
3. footer that has web page ownership information

For (2) :
- fixed the width of the form
- positioned the lock icon within the password input bar
- decreased the spacing between the footer elements (the texts within it)
- realigned other elements affected by the changes above

**Comment by Dandush03** [comment]
# :red_circle: Status: Required Changes :red_circle:
### Hey :wave: 
### Good attempts on this one :muscle: :+1: 

## Your project looks great! but is a very important thing you have to consider before submitting another code review :point_down: 

- [ ]  :one: You need to [Set-up Linter](https://github.com/microverseinc/linters-config/tree/master/css) correctly in order to get this project approved.
  > I can see that you had added a stickler file but your PR is not running through the checks.
#### you're receiving the fallowing error:
Screenshot from 2020-04-14 19-43-35

###### Your PR should look like this at the bottom: 
Screenshot from 2020-04-01 09-19-32
###### Not like this:
Screenshot from 2020-04-14 19-43-48

## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by jamestucker1988** [comment]
1)We fixed stickler.config.js issue and keep it running. 
2)We modeled our pages as expected in the assignment.
3)we fixed all linter errors.
4)We removed all issues pointed by TSE's.

**Comment by lekegitrepo** [comment]
### Hi @jamestucker1988 and @chelmerrox 👍 💯 🥇 
### You did a good job by fixing the stickler issue as required by the previous reviewer.
### This project is approved.

### Reviewed by Temitayo Adeleke.
- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Comment by jamestucker1988** [comment]
1)We fixed stickler.config.js issue and keep it running.
2)We modeled our pages as expected in the assignment.
3)we fixed all linter errors.
4)We removed all issues pointed by TSE's.

**Pull request merged**
